#!/bin/bash
# ============================================================================
# 06 — OFFLINE: build the rollback SQL from the state captured by 02.
#
# Connects to nothing. Reads <dir>/state/rls.csv and table_grants.csv and writes
# <dir>/rollback-restore-access.sql, which puts splits/members back exactly the
# way the OLD site needs them (row-level-security flag + the public key's table
# privileges as they were). Run it BEFORE the cutover; 03 and 04 refuse to touch
# production until this file exists.
#
# What rollback does NOT undo (by design — all harmless to the old site): the
# added columns, tables and functions stay. Splits created on the new version
# will not display correctly on the old site.
#
# Usage:
#   bash scripts/cutover/06-rollback-prepare.sh --dir backups/<folder from 01>
# ============================================================================
source "$(dirname "${BASH_SOURCE[0]}")/_common.sh"
usage() { sed -n 2,17p "${BASH_SOURCE[0]}"; }

parse_args "$@"
[ -n "$BACKUP_DIR" ] && [ -f "$BACKUP_DIR/state/rls.csv" ] && [ -f "$BACKUP_DIR/state/table_grants.csv" ] \
  || die "--dir must be a backup folder that 02-capture-state.sh has completed"
SRC_REF="$(grep -E '^ref=' "$BACKUP_DIR/target.txt" | cut -d= -f2)"
echo "════════════════════════════════════════════════════════════════════"
echo "  06 — prepare rollback SQL            mode: OFFLINE (no database connection)"
echo "  from state captured on project: $SRC_REF"
echo "════════════════════════════════════════════════════════════════════"

OUT="$BACKUP_DIR/rollback-restore-access.sql"
umask 077
python3 - "$BACKUP_DIR" "$SRC_REF" > "$OUT" <<'PY'
import csv, sys, re
d, ref = sys.argv[1], sys.argv[2]
ident = re.compile(r'^[a-z_][a-z0-9_]*$')
TABLES = ("splits", "members")                      # the only tables the old site uses
ROLES = {"anon": "anon", "authenticated": "authenticated", "PUBLIC": "public"}
PRIVS = {"SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE", "REFERENCES", "TRIGGER"}
rls = {r["table_name"]: r["rls_enabled"] for r in csv.DictReader(open(f"{d}/state/rls.csv", newline=""))}
grants = [r for r in csv.DictReader(open(f"{d}/state/table_grants.csv", newline=""))
          if r["table_name"] in TABLES and r["grantee"] in ROLES and r["privilege_type"] in PRIVS]
print(f"-- Rollback: restore the access state of splits/members as captured from project {ref}.")
print("-- Generated by 06-rollback-prepare.sh. Review before use; applied by 07-rollback-apply.sh.")
print("-- Restores ONLY access (RLS flag + public-key table privileges). Data is not touched.")
print("begin;")
for t in TABLES:
    if t not in rls:
        sys.exit(f"state has no row for table {t} — cannot build a rollback")
    assert ident.match(t)
    if rls[t] in ("f", "false", "False"):
        print(f"alter table public.{t} disable row level security;")
    else:
        print(f"-- {t}: row level security was already ENABLED before cutover — left enabled (its policies were never dropped).")
for g in sorted(grants, key=lambda r: (r["table_name"], r["grantee"], r["privilege_type"])):
    print(f"grant {g['privilege_type'].lower()} on public.{g['table_name']} to {ROLES[g['grantee']]};")
if not grants:
    print("-- NOTE: the captured state shows NO table privileges for anon/authenticated/public.")
    print("-- The old site could not have worked through grants alone — check state/policies.csv and summary.txt.")
print("commit;")
PY
chmod go-rwx "$OUT"

echo
cat "$OUT"
echo
echo "✅ Written: $OUT"
echo "   Review it now. In a rollback you would run, in this order:"
echo "   1. vercel promote <previous production deployment url>      (old code back on the domain)"
echo "   2. bash scripts/cutover/07-rollback-apply.sh --target production --ref $SRC_REF --host <host> --dir \"$BACKUP_DIR\""
